name: Fly PR Review Apps

on:
  pull_request:
    types: [opened, reopened, synchronize, closed]

jobs:
  review_app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: superfly/fly-pr-review-apps@1.2.1
        with:
          fly-api-token: ${{ secrets.FLY_API_TOKEN }}
          org: personal
          name: ax-worker
